- id: doi:10.48550/arXiv.2204.01586
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
  date: 2022-08-28
  extra-links:
    - type: source
      link: https://arxiv.org/abs/2204.01586
  tags: ECCV-2022, 6D pose estimation

- id: doi:10.1109/ICIP46576.2022.9897919
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  extra-links:
    - type: source
      link: https://ieeexplore.ieee.org/abstract/document/9897919
      
- id: doi:10.48550/arXiv.2105.00149
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
  date: 2021-12-31
  extra-links:
    - type: source
      link: https://www.aaai.org/AAAI22Papers/AAAI-1584.FanZ.pdf.pdf
  tags: AAAI 2022, SLAM
  
- id: doi:10.1145/3524496
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: source
      link: https://dl.acm.org/doi/abs/10.1145/3524496
  tags: object pose detection
  
- id: doi:10.1109/ICASSP39728.2021.9414867
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: source
      link: https://ieeexplore.ieee.org/abstract/document/9414867
  tags: missing part detection, point cloud
  
- id: doi:10.48550/arXiv.2108.12790
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: source
      link: https://arxiv.org/abs/2108.12790v2
  tags: Place Recognition, point cloud
  
- id: doi:10.1109/ICTAI50040.2020.00172
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: source
      link: https://ieeexplore.ieee.org/abstract/document/9288277
  tags: 3D detection
  
- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
    - type: manubot
      link: https://greenelab.github.io/scihub-manuscript/
    - type: source
      link: https://github.com/greenelab/scihub-manuscript
      text: Manuscript source
    - type: source
      link: https://github.com/greenelab/scihub
      text: Analyses source
