- id: doi:10.48550/arXiv.2204.01586
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
  date: 2022-08-28
  extra-links:
    - type: source
      link: https://arxiv.org/abs/2204.01586
  tags: ECCV-2022, 6D pose estimation
    - 

- id: doi:10.1109/ICIP46576.2022.9897919
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  extra-links:
    - type: source
      link: https://ieeexplore.ieee.org/abstract/document/9897919

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
    - type: manubot
      link: https://greenelab.github.io/scihub-manuscript/
    - type: source
      link: https://github.com/greenelab/scihub-manuscript
      text: Manuscript source
    - type: source
      link: https://github.com/greenelab/scihub
      text: Analyses source
